### ISSUE TITLE
[FEATURE] Bug tracker

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/BDN-V3#4]
There should be a bug tracker for scripts, could be based on [this](https://github.com/lgandelin/BugtrackerBundle).
- [ ] Base project on scripts within git
- [ ] Allow projects to be added and removed
- [ ] Allow project owners to add other script writers to project
- [ ] Login may be used by anyone on Parabot
- [ ] Allow project to be hidden or public, or even specific user groups
